##### 1. What is a Python library? Why do we use Python libraries?
- Numpy which means Numerical Python is a Python Library.
- Libraries have multiple built-in modules/functions which are very easy to use.
- Making use of Python libraries makes it convenient for the programmer as they wouldn't have to write the same code multiple times for different programs.
- They are used to create applications and models in various fields like ML, Data Science, 

##### 2. What is the difference between Numpy array and List?
- Array is a static DS which stores Homogeneous type of data.
- Lists are dynamic in nature and stores Heterogenius data.
- NumPy Array is a Python object which defines an N-dimensional array with rows and columns. 
- In Python, NumPy Array is preferred over lists because it takes up less memory and is faster and more convenient to use.

##### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
import numpy as np

arr = np.array([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr.shape

(3, 4)

In [10]:
arr.size

12

In [11]:
arr.ndim

2

##### 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [20]:
print(arr)

print("\n\n", arr[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 [5 6 7 8]


##### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
arr[2,3]

12

##### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [28]:
np.random.rand(3,3)

array([[0.61656575, 0.97667737, 0.37708528],
       [0.63584159, 0.40312489, 0.6799059 ],
       [0.89862856, 0.62602664, 0.76426498]])

##### 8. Describe the difference between np.random.rand and np.random.randn?
- random.rand() produces random numbers from a uniform distribution over the interval [0, 1)
- np.random.randn() generates random numbers from a standard normal distribution.

##### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [31]:
a = np.expand_dims(arr, axis=0)

In [32]:
a.ndim

3

##### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

##### 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python :
- Index wise multiplication
- Matix multiplication
- Add both the matix
- Subtact matix B from A
- Divide Matix B by A

In [35]:
# Index wise multiplication

a = np.array([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])

b = np.array([[1,2,3,4],[5, 6, 7, 8],[9, 10, 11, 12]])

a + b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [40]:
# Matrix Multiplication

a @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [41]:
np.add(a,b)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [45]:
np.subtract(b,a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
np.divide(a, b)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### 12. Which function in Numpy can be used to swap the byte order of an array?
- In Python, the Numpy library provides the function called “byteswap()”, which can be used to swap the bytes.
- byteswap() method does not work on arrays of strings.

##### 13. What is the significance of the np.linalg.inv function?
- numpy. linalg. inv() function to calculate the inverse of a matrix. 
- The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

##### 14. What does the np.reshape function do, and how is it used?
- The numpy.reshape() function shapes an array without changing the data of the array.

In [47]:
x = np.array([[2,3,4], [5,6,7]])      
np.reshape(x, (3, 2))

array([[2, 3],
       [4, 5],
       [6, 7]])

##### 15. What is broadcasting in Numpy?
- Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops.


In [48]:
a = np.zeros((3,4))

b = np.array([1,2,3,4])

a + b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])